apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe-service
spec:
  type: NodePort  
  selector:
    app: tic-tac-toe
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 80 
      nodePort: 30000
        

